apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := (index .Values.applications .Values.applicationName).config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
