apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/issuer: letsencrypt-prod
    appgw.ingress.kubernetes.io/health-probe-path: "/health-checks"
spec:
  rules:
  {{- range $host := include "hosts" . | fromYaml }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.Port }}
  {{- end }}
  tls:
  - hosts:
    {{- range $host := include "hosts" . | fromYarn }}
    - {{ $host }}
    {{- end }}
    secretName: {{ .Release.Name }}-tls
  
