apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/issuer: letsencrypt-prod
    appgw.ingress.kubernetes.io/health-probe-path: "/health-checks"
spec:
  rules:
  - host: {{ template "host" . }}
    http:
      paths:
        - path: /
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: {{ .Values.Port }}
          pathType: Prefix
  {{- if eq .Values.customdomainEnabled true }}
  - host: {{ .Values.customdomain }}
    http:
      paths:
        - path: /
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: {{ .Values.Port }}
          pathType: Prefix
  {{- end }}
  tls:
  - hosts:
    - {{ template "host" . }}
    secretName: {{ .Release.Name }}-tls
  {{- if eq .Values.customdomainEnabled true }}
  - hosts:
    - {{ .Values.customdomain }}
    secretName: {{ .Values.customdomain }}-tls
  {{- end }}
