apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/issuer: letsencrypt-prod
    appgw.ingress.kubernetes.io/health-probe-path: "/health-checks"
spec:
  rules:
  {{- $application := index .Values.applications .Values.applicationName }}
  {{- range $domain := $application.domains }}
  - host: {{ include "host" (dict "Release" $.Release "domain" $domain) }}
    http:
      paths:
        - path: /
          backend:
            service:
              name: {{ $.Release.Name }}
              port:
                number: {{ $.Values.Port }}
          pathType: Prefix
  {{- end }}
  {{- if eq .Values.environment "prod" }}
  {{- $application := index .Values.applications .Values.applicationName }}
  {{- range $custom_domain := $application.custom_domains }}
  - host: {{ $custom_domain }}
    http:
      paths:
        - path: /
          backend:
            service:
              name: {{ $.Release.Name }}
              port:
                number: {{ $.Values.Port }}
          pathType: Prefix
  {{- end }}
  {{- end }}
  tls:
  {{- range $domain := $application.domains }}
  - hosts:
    - {{ include "host" (dict "Release" $.Release "domain" $domain) }}
    secretName: {{ include "host" (dict "Release" $.Release "domain" $domain) }}-tls
  {{- end }}
  {{- if eq .Values.environment "prod" }}
  {{- range $custom_domain := $application.custom_domains }}
  - hosts:
    - {{ $custom_domain }}
    secretName: {{ $custom_domain }}-tls
  {{- end }}
  {{- end }}
