apiVersion: v1
kind: Service
metadata:
  labels: {{ include "common.labels" . | indent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.Port}}
      protocol: TCP
      targetPort: {{ .Values.Port}}
  selector: {{ include "common.labels" . | indent 4 }}
  type: ClusterIP