parameters:
- name: Environment
  type: string
- name: AgentAuthenticationBuildNumber
  type: string
- name: AgentBuildNumber
  type: string
- name: LogBuildNumber
  type: string
- name: MatchBuildNumber
  type: string
- name: OddBuildNumber
  type: string
- name: PlayerAuthenticationBuildNumber
  type: string
- name: PlayerBuildNumber
  type: string
- name: TicketBuildNumber
  type: string
- name: AgentPortalBuildNumber
  type: string
- name: PlayerPortalBuildNumber
  type: string

jobs:
- job: HelmUpgrade
  strategy:
    matrix:
      AgentAuthentication:
        applicationName: "agent-authentication"
        applicationBuildNo: ${{ parameters.AgentAuthenticationBuildNumber }}
      Agent:
        applicationName: "agent"
        applicationBuildNo: ${{ parameters.AgentBuildNumber }}
      Log:
        applicationName: "log"
        applicationBuildNo: ${{ parameters.LogBuildNumber }}
      Match:
        applicationName: "match"
        applicationBuildNo: ${{ parameters.MatchBuildNumber }}
      Odd:
        applicationName: "odd"
        applicationBuildNo: ${{ parameters.OddBuildNumber }}
      PlayerAuthentication:
        applicationName: "player-authentication"
        applicationBuildNo: ${{ parameters.PlayerAuthenticationBuildNumber }}
      Player:
        applicationName: "player"
        applicationBuildNo: ${{ parameters.PlayerBuildNumber }}
      Ticket:
        applicationName: "ticket"
        applicationBuildNo: ${{ parameters.TicketBuildNumber }}
      AgentPortal:
        applicationName: "agent-portal"
        applicationBuildNo: ${{ parameters.AgentPortalBuildNumber }}
      PlayerPortal:
        applicationName: "player-portal"
        applicationBuildNo: ${{ parameters.PlayerPortalBuildNumber }}
  steps:
  # - template: ../steps/KubectlInstaller.yaml
  # - template: ../steps/HelmInstaller.yaml
  - template: ../steps/DownloadHelmArtifact.yaml
    parameters:
      Environment: ${{ parameters.Environment }}
  - template: ../steps/HelmUpgrade.yaml
    parameters:
      Environment: ${{ parameters.Environment }}

