jobs:
- job: Publish_Docker_Artifacts
  pool:
    name: "$(AgentPool)"
  displayName: "Publish Docker Artifact to ${{ parameters.Environment }} Environment"
  strategy:
    matrix:
      Odd:
        WebAppName: "app-hnx-$(repository)-$(environment)-$(location)"
        application: "Odd"
        repository: "odd"
        Dockerfile: "Projects/Lottery/Player/OddsService/Lottery.Player.OddsService/Dockerfile"
        AppSettings: "Projects/Lottery/Player/OddsService/Lottery.Player.OddsService"
  steps:
  - template: ../steps/Replace_AppSettings_Files.yaml
  - template: ../steps/Publish_Docker_Artifacts.yaml
  - template: ../steps/Publish_Image_To_App_Service.yaml
  
