jobs:
- job: Publish_Docker_Artifacts
  pool:
    name: "$(AgentPool)"
  displayName: "Publish Docker Artifact to ${{ parameters.Environment }} Environment"
  strategy:
    matrix:
      Ticket:
        WebAppName: "app-hnx-$(repository)-$(environment)-$(location)"
        application: "Ticket"
        repository: "ticket"
        Dockerfile: "Projects/Lottery/Ticket/Lottery.Ticket.TicketService/Dockerfile"
        AppSettings: "Projects/Lottery/Ticket/Lottery.Ticket.TicketService"
  steps:
  - template: ../steps/Replace_AppSettings_Files.yaml
  - template: ../steps/Publish_Docker_Artifacts.yaml
  - template: ../steps/Publish_Image_To_App_Service.yaml
