parameters:
- name: Environment
  type: string

jobs:
- job: Publish_Docker_Artifacts
  pool:
    name: "$(AgentPool)"
  displayName: "Publish Docker Artifact to ${{ parameters.Environment }} Environment"
  strategy:
    matrix:
      Log:
        WebAppName: "app-hnx-$(repository)-$(environment)-$(location)"
        application: "Log"
        repository: "log"
        Dockerfile: "Common Services/LoggerService/HnMicro.LoggerService/Dockerfile"
        AppSettings: "Common Services/LoggerService/HnMicro.LoggerService"
  steps:
  - template: ../steps/Replace_AppSettings_Files.yaml
  - template: ../steps/Publish_Docker_Artifacts.yaml
  - template: ../steps/Publish_Image_To_App_Service.yaml
    parameters:
      Environment: ${{ parameters.Environment }}
