jobs:
- job: Publish_Docker_Artifacts
  pool:
    name: "$(AgentPool)"
  displayName: "Publish Docker Artifact to ${{ variables.environment }} Environment"
  strategy:
    matrix:
      SWallet.CustomerService:
        WebAppName: "app-hnx-$(repository)-$(environment)-$(location)"
        application: "SWallet.CustomerService"
        repository: "swallet.customerService"
        Dockerfile: "Projects/SWallet/Flow/SWallet.CustomerService/Dockerfile"
        AppSettings: "Projects/SWallet/Flow/SWallet.CustomerService"
  steps:
  #- template: ../steps/Replace_AppSettings_Files.yaml
  - template: ../steps/Publish_Docker_Artifacts.yaml
  #- template: ../steps/Publish_Image_To_App_Service.yaml
