parameters:
- name: Environment
  type: string

jobs:
- job: Publish_Docker_Artifacts
  pool:
    name: "$(AgentPool)"
  displayName: "Publish Docker Artifact to ${{ parameters.Environment }} Environment"
  strategy:
    matrix:
      Odd:
        WebAppName: "app-hnx-$(repository)-$(environment)-$(location)"
        application: "AdjustOdd"
        repository: "adjust-odd"
        Dockerfile: "Projects/Lottery/Tools/AdjustOddsService/Lottery.Tools.AdjustOddsService/Dockerfile"
        AppSettings: "Projects/Lottery/Tools/AdjustOddsService/Lottery.Tools.AdjustOddsService"
  steps:
  - template: ../steps/Replace_AppSettings_Files.yaml
  - template: ../steps/Publish_Docker_Artifacts.yaml
  - template: ../steps/Publish_Image_To_App_Service.yaml
    parameters:
      Environment: ${{ parameters.Environment }}
  
