jobs:
- job: Publish_Docker_Artifacts
  pool:
    name: "$(AgentPool)"
  displayName: "Publish Docker Artifact to ${{ variables.environment }} Environment"
  strategy:
    matrix:
      AllBet:
        WebAppName: "app-hnx-$(repository)-$(environment)-$(location)"
        application: "CockFight.Tools.Ga28"
        repository: "cockfight"
        Dockerfile: "Projects/Lottery/Tools/CockFight.Tools.Ga28/Dockerfile"
        AppSettings: "Projects/Lottery/Tools/CockFight.Tools.Ga28"
  steps:
  - template: ../steps/Replace_AppSettings_Files.yaml
  - template: ../steps/Publish_Docker_Artifacts.yaml
  - template: ../steps/Publish_Image_To_App_Service.yaml
