jobs:
- job: Publish_Docker_Artifacts
  pool:
    name: "$(AgentPool)"
  displayName: "Publish Docker Artifact to ${{ variables.environment }} Environment"
  strategy:
    matrix:
      AgentAuthentication:
        WebAppName: "app-hnx-$(repository)-$(environment)-$(location)"
        application: "AgentAuthentication"
        repository: "agent-authentication"
        Dockerfile: "Projects/Lottery/Agent/AuthenticationService/Lottery.Agent.AuthenticationService/Dockerfile"
        AppSettings: "Projects/Lottery/Agent/AuthenticationService/Lottery.Agent.AuthenticationService"
      Agent:
        WebAppName: "app-hnx-$(repository)-$(environment)-$(location)"
        application: "Agent"
        repository: "agent"
        Dockerfile: "Projects/Lottery/Agent/AgentService/Lottery.Agent.AgentService/Dockerfile"
        AppSettings: "Projects/Lottery/Agent/AgentService/Lottery.Agent.AgentService"
  steps:
  #  - template: ../steps/Publish_Docker_Artifacts.yaml
  - template: ../steps/Publish_Image_To_App_Service.yaml
    #  - template: ../steps/Replace_AppSettings_Files.yaml
