parameters:
- name: Environment
  type: string
- name: AgentAuthenticationBuildNumber
  type: string
- name: AgentBuildNumber
  type: string
- name: LogBuildNumber
  type: string
- name: OddBuildNumber
  type: string
- name: PlayerAuthenticationBuildNumber
  type: string
- name: PlayerBuildNumber
  type: string
- name: TicketBuildNumber
  type: string
- name: AgentPortalBuildNumber
  type: string
- name: PlayerPortalBuildNumber
  type: string

stages:
- stage: HelmUpgrade
  dependsOn: HelmPackage
  variables:
  - group: "${{ parameters.Environment }} Environment Variable Group"
  pool: $(pool)
  displayName: 'Helm upgrade'
  jobs:
  - template: ../jobs/HelmUpgrade.yaml
    parameters:
      Environment: ${{ parameters.Environment }}
      AgentAuthenticationBuildNumber: ${{ parameters.AgentAuthenticationBuildNumber }}
      AgentBuildNumber: ${{ parameters.AgentBuildNumber }}
      PlayerAuthenticationBuildNumber: ${{ parameters.PlayerAuthenticationBuildNumber }}
      PlayerBuildNumber: ${{ parameters.PlayerBuildNumber }}
      LogBuildNumber: ${{ parameters.LogBuildNumber }}
      OddBuildNumber: ${{ parameters.OddBuildNumber }}
      TicketBuildNumber: ${{ parameters.TicketBuildNumber }}
      AgentPortalBuildNumber: ${{ parameters.AgentPortalBuildNumber }}
      PlayerPortalBuildNumber: ${{ parameters.PlayerPortalBuildNumber }}