parameters:
- name: Environment
  type: string

stages:
- stage: HelmUpgrade
  variables:
  - group: "${{ parameters.Environment }} Environment Variable Group"
  pool: $(pool)
  displayName: 'Helm upgrade'
  jobs:
  - template: ../jobs/HelmUpgrade.yaml
    parameters:
      Environment: ${{ parameters.Environment }}