steps:
- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Terraform'
    azureResourceGroup: 'rg-hnx-${{ parameters.Environment }}-$(location)'
    kubernetesCluster: 'aks-hnx-${{ parameters.Environment }}-$(location)'
    namespace: '${{ parameters.Environment }}'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: '$(Pipeline.Workspace)/a/HnX-1.0.0.tgz'
    releaseName: 'app-hnx-$(applicationName)-${{ parameters.Environment }}-$(location)'
    overrideValues: 'applicationName=$(applicationName),applications.$(applicationName).image="$(DockerRegistryURL)/$(applicationName):$(applicationBuildNo)",customdomainEnabled=$(customdomainEnabled),customdomain=$(customdomain)'
    valueFile: '$(Pipeline.Workspace)/s/Helm/values-${{ parameters.Environment }}.yaml'
    arguments: '--create-namespace --timeout 60s'