steps:
- task: replacetokens@5
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)/Helm/'
    targetFiles: 'values-${{ parameters.Environment }}.yaml'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- task: HelmInstaller@0
  inputs:
    helmVersion: latest
    installKubectl: true