name: $(date:yyMMdd)$(rev:.rr)

trigger: none

pool:
  name: "Development Environment Agent Pool"

jobs:
- job: HelmPackageDevCentralUS
  displayName: 'Helm package'
  variables:
    - group: "Development Environment Variable Group"             
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'sed -i "s/Team/$(teamName)/g; s/Region/$(location)/g" values-dev.yaml'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Helm/'

  - task: replacetokens@5
    inputs:
      rootDirectory: '$(System.DefaultWorkingDirectory)/Helm/'
      targetFiles: 'values-dev.yaml'
      encoding: 'auto'
      tokenPattern: 'default'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      actionOnNoFiles: 'continue'
      enableTransforms: false
      enableRecursion: false
      useLegacyPattern: false
      enableTelemetry: true

  - task: HelmDeploy@0
    inputs:
      command: 'package'
      chartPath: '$(System.DefaultWorkingDirectory)/Helm/'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      artifact: 'PTG.PPPlus2 $(teamName)'
      publishLocation: 'pipeline'