name: $(date:yyMMdd)$(rev:.rr)

trigger:
  branches:
    include:
    - main
    - develop
  paths:
    include:
    - "Helm/*"
  batch: true

pool:
  name: "Development Environment Agent Pool"

parameters:
- name: Environment
  type: string
  default: dev
  values:
  - dev
  - test
  - prod
- name: AgentAuthenticationBuildNumber
  displayName: Agent Authentication Build Number
  default: latest
- name: AgentBuildNumber
  displayName: Agent Build Number
  default: latest
- name: LogBuildNumber
  displayName: Log Build Number
  default: latest
- name: OddBuildNumber
  displayName: Odd Build Number
  default: latest
- name: PlayerAuthenticationBuildNumber
  displayName: Player Authentication Build Number
  default: latest
- name: PlayerBuildNumber
  displayName: Player Build Number
  default: latest
- name: TicketBuildNumber
  displayName: Ticket Build Number
  default: latest
- name: AgentPortalBuildNumber
  displayName: Agent Portal Build Number
  default: latest
- name: PlayerPortalBuildNumber
  displayName: Player Portal Build Number
  default: latest

variables:
- template: ci/variables/${{ parameters.Environment }}.yaml

stages:
- template: ci/stages/HelmPackage.yaml
  parameters:
    Environment: ${{ parameters.Environment }}
- template: ci/stages/HelmUpgrade.yaml
  parameters:
    Environment: ${{ parameters.Environment }}
    AgentAuthenticationBuildNumber: ${{ parameters.AgentAuthenticationBuildNumber }}
    AgentBuildNumber: ${{ parameters.AgentBuildNumber }}
    PlayerAuthenticationBuildNumber: ${{ parameters.PlayerAuthenticationBuildNumber }}
    PlayerBuildNumber: ${{ parameters.PlayerBuildNumber }}
    LogBuildNumber: ${{ parameters.LogBuildNumber }}
    OddBuildNumber: ${{ parameters.OddBuildNumber }}
    TicketBuildNumber: ${{ parameters.TicketBuildNumber }}
    AgentPortalBuildNumber: ${{ parameters.AgentPortalBuildNumber }}
    PlayerPortalBuildNumber: ${{ parameters.PlayerPortalBuildNumber }}
