name: $(date:yyMMdd)$(rev:.rr)

trigger: none

pool:
  name: "Development Environment Agent Pool"

parameters:
- name: Environment
  type: string
  default: dev
  values:
  - dev
  - test
  - prod

variables:
- template: ci/variables/${{ parameters.Environment }}.yaml

stages:
- template: ci/stages/HelmPackage.yaml
  parameters:
    Environment: ${{ parameters.Environment }}
- template: ci/stages/HelmUpgrade.yaml
  parameters:
    Environment: ${{ parameters.Environment }}
