location: #{location}#
Port: 80
protocol: TCP
replicas: 1
environment: prod
averageUtilization:
  cpu: 75
  memory: 90
applications:
  agent-authentication:
    domains:
      - m8xs.io
      - m8xs.co
      - m8xs.net
    minReplicas: 1
    maxReplicas: 3
    image: "crhnxprodsoutheastasia.azurecr.io/agent-authentication"
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    config:
      ASPNETCORE_ENVIRONMENT: "Development"
      RedisConnections: "#{RedisConnections}#"
      DatabaseConnectionString: "#{DatabaseConnectionString}#"
  agent:
    domains:
      - m8xs.io
      - m8xs.co
      - m8xs.net
    minReplicas: 1
    maxReplicas: 3
    image: "crhnxprodsoutheastasia.azurecr.io/agent"
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    config:
      ASPNETCORE_ENVIRONMENT: "Development"
      RedisConnections: "#{RedisConnections}#"
      DatabaseConnectionString: "#{DatabaseConnectionString}#"
  log:
    domains:
      - m8xs.io
      - m8xs.co
      - m8xs.net
    minReplicas: 1
    maxReplicas: 3
    image: "crhnxprodsoutheastasia.azurecr.io/log"
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    config:
      ASPNETCORE_ENVIRONMENT: "Development"
      RedisConnections: "#{RedisConnections}#"
      DatabaseConnectionString: "#{DatabaseConnectionString}#"
  match:
    domains:
      - m8xs.io
      - m8xs.co
      - m8xs.net
    minReplicas: 1
    maxReplicas: 3
    image: "crhnxprodsoutheastasia.azurecr.io/match"
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    config:
      ASPNETCORE_ENVIRONMENT: "Development"
      RedisConnections: "#{RedisConnections}#"
      DatabaseConnectionString: "#{DatabaseConnectionString}#"
  odd:
    domains:
      - m8xs.io
      - m8xs.co
      - m8xs.net
    minReplicas: 1
    maxReplicas: 3
    image: "crhnxprodsoutheastasia.azurecr.io/odd"
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    config:
      ASPNETCORE_ENVIRONMENT: "Development"
      RedisConnections: "#{RedisConnections}#"
      DatabaseConnectionString: "#{DatabaseConnectionString}#"
  player-authentication:
    domains:
      - m8xs.io
      - m8xs.co
      - m8xs.net
    minReplicas: 1
    maxReplicas: 3
    image: "crhnxprodsoutheastasia.azurecr.io/player-authentication"
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    config:
      ASPNETCORE_ENVIRONMENT: "Development"
      RedisConnections: "#{RedisConnections}#"
      DatabaseConnectionString: "#{DatabaseConnectionString}#"
  player:
    domains:
      - m8xs.io
      - m8xs.co
      - m8xs.net
    minReplicas: 1
    maxReplicas: 3
    image: "crhnxprodsoutheastasia.azurecr.io/player"
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    config:
      ASPNETCORE_ENVIRONMENT: "Development"
      RedisConnections: "#{RedisConnections}#"
      DatabaseConnectionString: "#{DatabaseConnectionString}#"
  ticket:
    domains:
      - m8xs.io
      - m8xs.co
      - m8xs.net
    minReplicas: 1
    maxReplicas: 3
    image: "crhnxprodsoutheastasia.azurecr.io/ticket"
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    config:
      ASPNETCORE_ENVIRONMENT: "Development"
      RedisConnections: "#{RedisConnections}#"
      DatabaseConnectionString: "#{DatabaseConnectionString}#"
  agent-portal:
    domains:
      - m8xs.io
      - m8xs.co
      - m8xs.net
    custom_domains:
      - m8xs.io
      - m8xs.co
      - m8xs.net
    minReplicas: 1
    maxReplicas: 3
    image: "crhnxprodsoutheastasia.azurecr.io/agent-portal"
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    config:
      RedisConnections: "#{RedisConnections}#"
      DatabaseConnectionString: "#{DatabaseConnectionString}#"
  player-portal:
    domains:
      - m8xs.io
      - m8xs.co
      - m8xs.net
    custom_domains:
      - agent.m8xs.io
      - agent.m8xs.co
      - agent.m8xs.net
      - agent.m8xs.com
    minReplicas: 1
    maxReplicas: 3
    image: "crhnxprodsoutheastasia.azurecr.io/player-portal"
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    config:
      RedisConnections: "#{RedisConnections}#"
      DatabaseConnectionString: "#{DatabaseConnectionString}#"
