INSERT INTO Channels (Name, RegionId, DayOfWeeks) 
VALUES 
	(N'Hà Nội', 1, '1,4'),
	(N'Quảng Ninh', 1, '2'),
	(N'Bắc Ninh', 1, '3'),
	(N'Hải Phòng', 1, '5'),
	(N'Nam Định', 1, '6'),
	(N'Thái Bình', 1, '0'),
	(N'Phú Yên', 2, '1'),
	(N'Thừa Thiên Huế', 2, '1'),
	(N'Đắc Lắc', 2, '2'),
	(N'Quảng Nam', 2, '2'),
	(N'Đà Nẵng', 2, '3,6'),
	(N'Khánh Hòa', 2, '0,3'),
	(N'Bình Định', 2, '4'),
	(N'Quảng Bình', 2, '4'),
	(N'Quảng Trị', 2, '4'),
	(N'Gia Lai', 2, '5'),
	(N'Ninh Thuận', 2, '5'),
	(N'Đắc Nông', 2, '6'),
	(N'Quảng Ngãi', 2, '6'),
	(N'Kon Tum', 2, '0'),
	(N'TP. Hồ Chí Minh', 3, '1,6'),
	(N'Cà Mau', 3, '1'),
	(N'Đồng Tháp', 3, '1'),
	(N'Bạc Liêu', 3, '2'),
	(N'Bến Tre', 3, '2'),
	(N'Vũng Tàu', 3, '2'),
	(N'Đồng Nai', 3, '3'),
	(N'Sóc Trăng', 3, '3'),
	(N'Cần Thơ', 3, '3'),
	(N'An Giang', 3, '4'),
	(N'Bình Thuận', 3, '4'),
	(N'Tây Ninh', 3, '4'),
	(N'Bình Dương', 3, '5'),
	(N'Trà Vinh', 3, '5'),
	(N'Vĩnh Long', 3, '5'),
	(N'Bình Phước', 3, '6'),
	(N'Hậu Giang', 3, '6'),
	(N'Long An', 3, '6'),
	(N'Đà Lạt', 3, '0'),
	(N'Kiên Giang', 3, '0');